# Site settings
title: My Musings on Music
email: your-email@domain.com
description: "I believe music can be a form of perfection - with nothing added or subtracted, flawless just the way it is. This is my take on the music and the people that make it. It's mostly about jazz and blues. Content and design by Å½an Anderle"
baseurl: ""
url: "http://musingsonmusic.com"
paginate: 5

# Build settings
markdown: kramdown
permalink: pretty
destination: /home/zan/websites/zanderle.github.io
exclude: [LICENSE, README.md, feed.xml]

#Social media
twitter_username: z_anderle
github_username:  zanderle
twitter_url: "https://twitter.com/z_anderle"
instagram_url: "https://instagram.com/zanderle"

#RSS feed generator
name: My Musings on Music
